#!/usr/bin/env bash
# Displays a list of currently running processes.
#   Shows all processes, for all users, including those
#+  which might not have a TTY.

ps -e -o pid,user,tty,comm,args --forest
